// <auto-generated />
using System;
using HeThongTuyenDung.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongTuyenDung.Migrations
{
    [DbContext(typeof(TuyenDungDbContext))]
    partial class TuyenDungDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongTuyenDung.Models.AnhCongTy", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<string>("MoTaAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaCongTy");

                    b.ToTable("AnhCongTys");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.CapBacCongViec", b =>
                {
                    b.Property<int>("MaCapBac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCapBac"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenCapBac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCapBac");

                    b.ToTable("CapBacCongViecs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.ChungChi", b =>
                {
                    b.Property<int>("MaChungChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChungChi"));

                    b.Property<string>("DonViCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChungChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaChungChi");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.ToTable("ChungChis");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.CongTy", b =>
                {
                    b.Property<int>("MaCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongTy"));

                    b.Property<string>("AnhBia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("DaXacThuc")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinhVuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuyMo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaCongTy");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("CongTys");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DanhGiaPhongVan", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("DeXuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("DiemManh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiemYeu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaPhongVan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDanhGia")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDanhGiaUserMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("PhongVanMaPhongVan")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("NguoiDanhGiaUserMaNguoiDung");

                    b.HasIndex("PhongVanMaPhongVan");

                    b.ToTable("DanhGiaPhongVans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DanhMucCongViec", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("BieuTuong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucCongViecs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DonUngTuyen", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViTien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DuAn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DuongDanCV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HocVan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KinhNghiemLamViec")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KyNang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("LuongMongMuon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LyDoUngTuyen")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaTin")
                        .HasColumnType("int");

                    b.Property<decimal?>("MucLuongMongMuon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MucTieu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayUngTuyen")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NguonUngTuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinBoSung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ThuNgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TinTuyenDungMaTin")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDon");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.HasIndex("TinTuyenDungMaTin");

                    b.ToTable("DonUngTuyens");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DuAn", b =>
                {
                    b.Property<int>("MaDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuAn"));

                    b.Property<string>("CongNgheSuDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DangThucHien")
                        .HasColumnType("bit");

                    b.Property<int?>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("LienKetDuAn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaDuAn");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.ToTable("DuAns");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.HoSoUngVien", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<bool>("CoTheNuocNgoai")
                        .HasColumnType("bit");

                    b.Property<bool>("CongKhaiHoSo")
                        .HasColumnType("bit");

                    b.Property<string>("CongTyHienTai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CongViecHienTai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DangTimViec")
                        .HasColumnType("bit");

                    b.Property<string>("DiaDiemMongMuon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViTien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiCongViecMongMuon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<decimal?>("MucLuongHienTai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MucLuongMongMuon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<string>("ViTriMongMuon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique()
                        .HasFilter("[MaNguoiDung] IS NOT NULL");

                    b.ToTable("HoSoUngViens");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.HocVan", b =>
                {
                    b.Property<int>("MaHocVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVan"));

                    b.Property<string>("BangCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DangHoc")
                        .HasColumnType("bit");

                    b.Property<int?>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaHocVan");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.ToTable("HocVans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KinhNghiem", b =>
                {
                    b.Property<int>("MaKinhNghiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKinhNghiem"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("bit");

                    b.Property<int?>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKinhNghiem");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.ToTable("KinhNghiems");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KyNang", b =>
                {
                    b.Property<int>("MaKyNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyNang"));

                    b.Property<string>("BieuTuong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiKyNang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKyNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKyNang");

                    b.ToTable("KyNangs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KyNangTuyenDung", b =>
                {
                    b.Property<int>("MaTin")
                        .HasColumnType("int");

                    b.Property<int>("MaKyNang")
                        .HasColumnType("int");

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<int>("CapDo")
                        .HasColumnType("int");

                    b.Property<int>("KyNangMaKyNang")
                        .HasColumnType("int");

                    b.Property<int>("TinTuyenDungMaTin")
                        .HasColumnType("int");

                    b.HasKey("MaTin", "MaKyNang");

                    b.HasIndex("KyNangMaKyNang");

                    b.HasIndex("TinTuyenDungMaTin");

                    b.ToTable("KyNangTuyenDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KyNangUngVien", b =>
                {
                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<int>("MaKyNang")
                        .HasColumnType("int");

                    b.Property<int>("CapDo")
                        .HasColumnType("int");

                    b.Property<int>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<int>("KyNangMaKyNang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.HasKey("MaHoSo", "MaKyNang");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.HasIndex("KyNangMaKyNang");

                    b.ToTable("KyNangUngViens");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.LoaiCongViec", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiCongViecs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.PhongVan", b =>
                {
                    b.Property<int>("MaPhongVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongVan"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DonUngTuyenMaDon")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhongVan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDon")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoUserMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhongVan");

                    b.HasIndex("DonUngTuyenMaDon");

                    b.HasIndex("NguoiTaoUserMaNguoiDung");

                    b.ToTable("PhongVans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.QuyenHan", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.ToTable("QuyenHans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaLienQuan")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.TinDaLuu", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTin")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLuu")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("TinTuyenDungMaTin")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung", "MaTin");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.HasIndex("TinTuyenDungMaTin");

                    b.ToTable("TinDaLuus");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.TinTuyenDung", b =>
                {
                    b.Property<int>("MaTin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTin"));

                    b.Property<int?>("CapBacCongViecMaCapBac")
                        .HasColumnType("int");

                    b.Property<int?>("CongTyMaCongTy")
                        .HasColumnType("int");

                    b.Property<int?>("DanhMucCongViecMaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoTuoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DonViTien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("GapTuyen")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("HanNop")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HienThiLuong")
                        .HasColumnType("bit");

                    b.Property<int?>("KinhNghiemDen")
                        .HasColumnType("int");

                    b.Property<int?>("KinhNghiemTu")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiCongViecMaLoai")
                        .HasColumnType("int");

                    b.Property<decimal?>("LuongDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LuongTu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int?>("MaCapBac")
                        .HasColumnType("int");

                    b.Property<int?>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoUserMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuyenLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThanhPho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("YeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTin");

                    b.HasIndex("CapBacCongViecMaCapBac");

                    b.HasIndex("CongTyMaCongTy");

                    b.HasIndex("DanhMucCongViecMaDanhMuc");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.HasIndex("LoaiCongViecMaLoai");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.HasIndex("NguoiTaoUserMaNguoiDung");

                    b.ToTable("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.UngVienDaLuu", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<int>("HoSoUngVienMaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLuu")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung", "MaHoSo");

                    b.HasIndex("HoSoUngVienMaHoSo");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("UngVienDaLuus");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.VaiTroQuyenHan", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaVaiTro", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VaiTroQuyenHans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.AnhCongTy", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.CongTy", "CongTy")
                        .WithMany("AnhCongTys")
                        .HasForeignKey("MaCongTy");

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.ChungChi", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("ChungChis")
                        .HasForeignKey("HoSoUngVienMaHoSo");

                    b.Navigation("HoSoUngVien");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.CongTy", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithMany("CongTys")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DanhGiaPhongVan", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDanhGiaUser")
                        .WithMany("DanhGiaPhongVans")
                        .HasForeignKey("NguoiDanhGiaUserMaNguoiDung");

                    b.HasOne("HeThongTuyenDung.Models.PhongVan", "PhongVan")
                        .WithMany("DanhGiaPhongVans")
                        .HasForeignKey("PhongVanMaPhongVan");

                    b.Navigation("NguoiDanhGiaUser");

                    b.Navigation("PhongVan");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DonUngTuyen", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("DonUngTuyens")
                        .HasForeignKey("HoSoUngVienMaHoSo");

                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.HasOne("HeThongTuyenDung.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("DonUngTuyens")
                        .HasForeignKey("TinTuyenDungMaTin");

                    b.Navigation("HoSoUngVien");

                    b.Navigation("NguoiDung");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DuAn", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("DuAns")
                        .HasForeignKey("HoSoUngVienMaHoSo");

                    b.Navigation("HoSoUngVien");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.HoSoUngVien", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithOne("HoSoUngVien")
                        .HasForeignKey("HeThongTuyenDung.Models.HoSoUngVien", "MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.HocVan", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("HocVans")
                        .HasForeignKey("HoSoUngVienMaHoSo");

                    b.Navigation("HoSoUngVien");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KinhNghiem", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("KinhNghiems")
                        .HasForeignKey("HoSoUngVienMaHoSo");

                    b.Navigation("HoSoUngVien");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KyNangTuyenDung", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.KyNang", "KyNang")
                        .WithMany("KyNangTuyenDungs")
                        .HasForeignKey("KyNangMaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTuyenDung.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("KyNangTuyenDungs")
                        .HasForeignKey("TinTuyenDungMaTin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KyNangUngVien", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("KyNangUngViens")
                        .HasForeignKey("HoSoUngVienMaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTuyenDung.Models.KyNang", "KyNang")
                        .WithMany("KyNangUngViens")
                        .HasForeignKey("KyNangMaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoUngVien");

                    b.Navigation("KyNang");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.NguoiDung", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.PhongVan", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.DonUngTuyen", "DonUngTuyen")
                        .WithMany("PhongVans")
                        .HasForeignKey("DonUngTuyenMaDon");

                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiTaoUser")
                        .WithMany("PhongVansTao")
                        .HasForeignKey("NguoiTaoUserMaNguoiDung");

                    b.Navigation("DonUngTuyen");

                    b.Navigation("NguoiTaoUser");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.ThongBao", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.TinDaLuu", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithMany("TinDaLuus")
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTuyenDung.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("TinDaLuus")
                        .HasForeignKey("TinTuyenDungMaTin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.TinTuyenDung", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.CapBacCongViec", "CapBacCongViec")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("CapBacCongViecMaCapBac");

                    b.HasOne("HeThongTuyenDung.Models.CongTy", "CongTy")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("CongTyMaCongTy");

                    b.HasOne("HeThongTuyenDung.Models.DanhMucCongViec", "DanhMucCongViec")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("DanhMucCongViecMaDanhMuc");

                    b.HasOne("HeThongTuyenDung.Models.LoaiCongViec", "LoaiCongViec")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("LoaiCongViecMaLoai");

                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiTaoUser")
                        .WithMany()
                        .HasForeignKey("NguoiTaoUserMaNguoiDung");

                    b.Navigation("CapBacCongViec");

                    b.Navigation("CongTy");

                    b.Navigation("DanhMucCongViec");

                    b.Navigation("LoaiCongViec");

                    b.Navigation("NguoiDung");

                    b.Navigation("NguoiTaoUser");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.UngVienDaLuu", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.HoSoUngVien", "HoSoUngVien")
                        .WithMany("UngVienDaLuus")
                        .HasForeignKey("HoSoUngVienMaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTuyenDung.Models.NguoiDung", "NguoiDung")
                        .WithMany("UngVienDaLuus")
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoUngVien");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.VaiTroQuyenHan", b =>
                {
                    b.HasOne("HeThongTuyenDung.Models.QuyenHan", "QuyenHan")
                        .WithMany("VaiTroQuyenHans")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTuyenDung.Models.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyenHans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyenHan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.CapBacCongViec", b =>
                {
                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.CongTy", b =>
                {
                    b.Navigation("AnhCongTys");

                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DanhMucCongViec", b =>
                {
                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.DonUngTuyen", b =>
                {
                    b.Navigation("PhongVans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.HoSoUngVien", b =>
                {
                    b.Navigation("ChungChis");

                    b.Navigation("DonUngTuyens");

                    b.Navigation("DuAns");

                    b.Navigation("HocVans");

                    b.Navigation("KinhNghiems");

                    b.Navigation("KyNangUngViens");

                    b.Navigation("UngVienDaLuus");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.KyNang", b =>
                {
                    b.Navigation("KyNangTuyenDungs");

                    b.Navigation("KyNangUngViens");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.LoaiCongViec", b =>
                {
                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.NguoiDung", b =>
                {
                    b.Navigation("CongTys");

                    b.Navigation("DanhGiaPhongVans");

                    b.Navigation("HoSoUngVien");

                    b.Navigation("PhongVansTao");

                    b.Navigation("ThongBaos");

                    b.Navigation("TinDaLuus");

                    b.Navigation("UngVienDaLuus");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.PhongVan", b =>
                {
                    b.Navigation("DanhGiaPhongVans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.QuyenHan", b =>
                {
                    b.Navigation("VaiTroQuyenHans");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.TinTuyenDung", b =>
                {
                    b.Navigation("DonUngTuyens");

                    b.Navigation("KyNangTuyenDungs");

                    b.Navigation("TinDaLuus");
                });

            modelBuilder.Entity("HeThongTuyenDung.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("VaiTroQuyenHans");
                });
#pragma warning restore 612, 618
        }
    }
}
